import Vue from 'vue'
import { Button, Loading, Row, Col, Menu, MenuItem, MenuItemGroup, Submenu, Message, Breadcrumb, BreadcrumbItem, Cascader, DatePicker, Upload, Dialog, Autocomplete, Link, Pagination, Tree, Scrollbar, Dropdown, DropdownMenu, DropdownItem, Card, Table, TableColumn, Form, FormItem, Input, Select, Option, Tag } from 'element-ui'
Vue.use(Button)
Vue.use(Loading)
Vue.use(Row)
Vue.use(Col)
Vue.use(Menu)
Vue.use(MenuItem)
Vue.use(MenuItemGroup)
Vue.use(Submenu)
Vue.use(Breadcrumb)
Vue.use(BreadcrumbItem)
Vue.use(Cascader)
Vue.use(DatePicker)
Vue.use(Upload)
Vue.use(Dialog)
Vue.use(Autocomplete)
Vue.use(Link)
Vue.use(Pagination)
Vue.use(Tree)
Vue.use(Scrollbar)
Vue.use(Dropdown)
Vue.use(DropdownMenu)
Vue.use(DropdownItem)
Vue.use(Card)
Vue.use(Table)
Vue.use(TableColumn)
Vue.use(Form)
Vue.use(FormItem)
Vue.use(Input)
Vue.use(Select)
Vue.use(Option)
Vue.use(Tag)
// Vue.use(ElementUI, { size: 'medium' })
Vue.prototype.$message = Message
